### ISSUE TITLE
Display events in descending order based on date

### ISSUE THREAD

**Issue by rashidalabri** [hackclub/hackathons-v1#5]
Currently, the events are displayed in ascending order. It would be more useful if they were displayed in descending order, as you wouldn't need to scroll further to find an event to sign up for.

**Comment by lachlanjc** [comment]
I agree the sorting isn't the right order, I'd support only showing events in the future, from soonest to furthest, with the toggle for seeing past events

**Comment by maxwofford** [comment]
What if the toggle had the following options:

- events in the future
- events from this school-year
- events from all-time

All these would still be sorted by ascending date (we don’t want events too far off showing up at the top), but the default option would be events in the future.

**Comment by lachlanjc** [comment]
Closed by #27
